# Generated by Django 3.1.3 on 2020-12-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
