# Generated by Django 3.1.3 on 2020-12-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0002_homecontent_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('homecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='korbex.homecontent')),
                ('author', models.CharField(help_text='type your name', max_length=20)),
            ],
            bases=('korbex.homecontent',),
        ),
    ]
