# Generated by Django 3.1.3 on 2020-12-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
