# Generated by Django 3.1.3 on 2020-12-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0004_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField(help_text='input your text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('data_add', models.DateField(auto_now=True)),
                ('author', models.CharField(help_text='type your name', max_length=20)),
            ],
        ),
    ]
