# Generated by Django 3.1.3 on 2020-12-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0006_auto_20201223_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cena',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_repair',
            field=models.CharField(help_text='Nazwa naprawy(wymiana kierownicy)', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='type_repair',
            field=models.CharField(help_text='Typ naprawy(kierownica, hamulca itp)', max_length=50),
        ),
    ]
