# Generated by Django 3.1.3 on 2020-12-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0007_auto_20201223_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name_repair',
            field=models.CharField(help_text='Nazwa naprawy(wymiana kierownicy)', max_length=50, unique=True),
        ),
    ]
