# Generated by Django 3.1.3 on 2020-12-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0008_auto_20201224_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='cena',
            new_name='price',
        ),
    ]
