# Generated by Django 3.1.3 on 2020-12-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0012_auto_20201229_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproducts',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
