# Generated by Django 3.1.3 on 2020-12-31 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0013_auto_20201231_0632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreProducts',
        ),
    ]
