# Generated by Django 3.1.3 on 2020-12-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0014_delete_storeproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name_product', models.CharField(max_length=40, unique=True)),
                ('incomplete_description', models.TextField(max_length=120)),
                ('continue_description', models.TextField(blank=True, max_length=500, null=True)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
