# Generated by Django 3.1.3 on 2021-01-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0016_auto_20201231_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactData',
        ),
    ]
