# Generated by Django 3.1.3 on 2021-01-01 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0017_auto_20210101_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdata',
            old_name='facebok',
            new_name='facebook',
        ),
    ]
