# Generated by Django 3.1.3 on 2021-01-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0019_auto_20210101_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdata',
            old_name='telefon',
            new_name='telephone',
        ),
    ]
