# Generated by Django 3.1.3 on 2021-01-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0020_auto_20210101_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type_repair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='korbex.typerepair'),
        ),
        migrations.AlterField(
            model_name='typerepair',
            name='type_repair',
            field=models.CharField(help_text='Typ naprawy(kierownica, hamulca itp)', max_length=50, unique=True),
        ),
    ]
