# Generated by Django 3.1.3 on 2021-01-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0021_auto_20210117_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type_repair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='korbex.typerepair'),
        ),
    ]
