# Generated by Django 3.1.3 on 2021-02-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0024_auto_20210208_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='telephone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='working_day',
            field=models.CharField(choices=[('1.Poniedziałek', 'Poniedziałek'), ('2.Wtorek', 'Wtorek'), ('3.Środa', 'Środa'), ('4.Czwartek', 'Czwartek'), ('5.Piątek', 'Piątek'), ('6.Sobota', 'Sobota'), ('7.Niedzelia', 'Niedzelia')], max_length=20, verbose_name='Dzień tygodnia'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='working_hours',
            field=models.CharField(max_length=25, verbose_name='Godziny pracy'),
        ),
    ]
