# Generated by Django 3.1.3 on 2021-02-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korbex', '0025_auto_20210211_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='data_add',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='storeproducts',
            name='continue_description',
            field=models.TextField(blank=True, null=True, verbose_name='Pełny opis towaru'),
        ),
        migrations.AlterField(
            model_name='storeproducts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_image', verbose_name='Obrazek do towaru'),
        ),
        migrations.AlterField(
            model_name='storeproducts',
            name='incomplete_description',
            field=models.TextField(max_length=180, verbose_name='Krótki opis towaru'),
        ),
        migrations.AlterField(
            model_name='storeproducts',
            name='name_product',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nazwa towaru'),
        ),
        migrations.AlterField(
            model_name='storeproducts',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Cena towaru'),
        ),
    ]
